name: IaC Scan
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install AWS CLI tool & CDK Synth
        shell: bash
        run: |
          pip install -r requirements.txt && npm install -g aws-cdk && cdk synth
      - name: ls
        shell: bash
        run: |
          ls cdk.out
      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./cdk.out
