name: IaC Scan
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install AWS CLI tool & CDK Synth
        shell: bash
        run: |
          npm install -g aws-cdk && pip install -r requirements.txt

      - name: ls
        shell: bash
        run: |
          ls
